### ISSUE TITLE
Issue tracker

### ISSUE THREAD

**Issue by emilk** [not-fl3/egui-miniquad#15]
This is a tracking issue for some things still lacking

* [ ] Copy/paste in browser
* [ ] Cursor changes on MacOS (not implemented in microquad yet)
* [ ] Only redraw on changes/events (reactive mode) to save CPU

**Comment by not-fl3** [comment]
>  Copy/paste in browser

Just tried in some of @optozorax's demos and it works, not quite sure is it something made by @optozorax's in emigui-macroquad or is it available out of the box with egui-miniquad

**Comment by emilk** [comment]
Does it work for you in https://not-fl3.github.io/egui-miniquad/ ? For me it doesn't work (Firefox+Mac)

**Comment by not-fl3** [comment]
It does not, but I got plenty of errors in the console like "Version mismatch: gl.js version is: 0.1.22, rust sapp-wasm crate version is: 0.1.23"
So maybe updating gl.js will do the job?

**Comment by not-fl3** [comment]
Small side note: https://github.com/not-fl3/egui-miniquad/blob/master/build_web.sh#L12

`wasm-strip` call on the rust's output wasm will reduce .wasm file size from 4mb to 2mb :)

**Comment by akhilman** [comment]
I'm interested in "Only redraw on changes/events (reactive mode) to save CPU".
My current idea is to render egui to offscreen buffer and reuse the same image when there is no input or no redraw required.
I also think to use the value of the alpha channel of the buffer for the input event routing.
